
export interface Language {
  code: string;
  name: string;
}

export interface Note {
  id: string;
  timestamp: string; // ISO date string
  sourceSegment: string; // The ~500 words of translated text
  summary: string; // The note generated by Gemini
}

export interface HistoryItem {
  id: string; // Unique identifier, e.g., timestamp of saving
  title: string; // User-editable title, initially AI-generated
  timestamp: string; // ISO date string of when the session was saved
  sourceText: string;
  translatedFullText: string;
  notes: Note[];
  sourceLang: string;
  targetLang: string;
  uiLang: string;
  translationMode: string; // 'realtime' | 'composed'
}
